### ISSUE TITLE
报错+奈飞解锁测试不了，前几天还正常的。

### ISSUE THREAD

**Issue by cmazfuture** [PauperZ/SSRSpeedN#22]
版本是SSRSpeedN-1.03
报错+奈飞解锁测试不了，前几天还正常的。
![QQ截图20220331230603](https://user-images.githubusercontent.com/71751136/161088683-3b1da57e-d64c-4321-9d8d-1f77ef19521d.png)
![QQ截图20220331231028](https://user-images.githubusercontent.com/71751136/161088780-752212b6-a835-4762-a465-f55ae2992a3b.png)

**Comment by q13433801326** [comment]
同样
