### ISSUE TITLE
windows7的疑问

### ISSUE THREAD

**Issue by INZEEN** [PauperZ/SSRSpeedN#25]
这是什么意思 我看作者测试过的系统只有win10,win7是不能用吗
![Snipaste_2022-04-07_10-29-18](https://user-images.githubusercontent.com/97651641/162108568-302b1669-86f8-4172-9bb3-a0a11c1a1534.png)

**Comment by PauperZ** [comment]
@INZEEN 没装依赖...

**Comment by INZEEN** [comment]
> @INZEEN没装依赖...

怎么说呢…看了详细适用教程 在 以管理员身份执行 开始测速.bat , 输入 2 并回车，bat脚本会自动安装依赖，程序默认已集成，理论上应该无需安装。这一条出现了问题我按了2回车之后出现了一大串红字

**Comment by PauperZ** [comment]
@INZEEN 个人网络问题，网络质量差的第三方库不开系统代理确实不太好装

**Comment by guduobai** [comment]
pip 安装源改成国内的，比如阿里云。不然依赖大概率安装失败
