### ISSUE TITLE
测速时显示"Import Hint重要提示"

### ISSUE THREAD

**Issue by NtskeyTeams** [PauperZ/SSRSpeedN#26]
显示如图，但不进行测速就关了
![image](https://user-images.githubusercontent.com/75188896/163669831-4a222e75-8a51-4aa1-a450-c77c35f5da89.png)

**Comment by hedw1gP** [comment]
`Press ENTER to continue`

or, remove the following lines (74-77) in `main.py` if you really don't want to see it:

```python
	print("****** Import Hint 重要提示******")
	print("ChenBilly yyds！")
	print("*********************************")
	input("Press ENTER to conitnue or Crtl+C to exit.")
```
