### ISSUE TITLE
默认运行程序是管理员权限

### ISSUE THREAD

**Issue by 648480505** [PauperZ/SSRSpeedN#48]
有没有办法不用管理员权限运行？

**Comment by lrs95** [comment]
仅适用于专业版以上系统
1、开始-运行-gpedit.msc，左侧树形图找到本地计算机策略->计算机配置->Windows设置->安全设置->本地策略->安全选项，按名称排序，找到用户账户控制的配置：以管理员批准模式运行所有管理员：
![image](https://user-images.githubusercontent.com/24587454/218266100-4634e06b-9924-4996-82fb-3b59a6aa27b1.png)
2、把这个开关设为已启用，默认应该就是非管理员权限了吧。反正我这个这么设置就是这样的，禁用后就默认管理员运行所有程序了，你可以试试。

**Comment by 648480505** [comment]
> 只适用于以上系统， -运行-gpedit.msc，左侧左侧找到计算机策略策略->> windows-> windows设置->>>>>>>>>>>>>>>>>>>>>> >安全安全，找到用户的：以管理人员运行： 2，运行运行运行：默认管理人员运行所有程序了，你可以试一试。 ![图片](https://user-images.githubusercontent.com/24587454/218266100-4634e06b-9924-4996-82fb-3b59a6aa27b1.png)

我用的是内置管理员账户，我的所有操作都是管理员操作，组策略试过了，没用（最高权限，组策略没用吧）。谢谢你的帮助，放弃使用这个测速程序了。

**Comment by PauperZ** [comment]
> > 只适用于以上系统， -运行-gpedit.msc，左侧左侧找到计算机策略策略->> windows-> windows设置->>>>>>>>>>>>>>>>>>>>>> >安全安全，找到用户的：以管理人员运行： 2，运行运行运行：默认管理人员运行所有程序了，你可以试一试。 ![图片](https://user-images.githubusercontent.com/24587454/218266100-4634e06b-9924-4996-82fb-3b59a6aa27b1.png)
> 
> 我用的是内置管理员账户，我的所有操作都是管理员操作，组策略试过了，没用（最高权限，组策略没用吧）。谢谢你的帮助，放弃使用这个测速程序了。

测速的时候可以直接用命令行，不用cmd指令也行

**Comment by 648480505** [comment]
> 
嗯

**Comment by 648480505** [comment]
> 仅适用于以上系统系统， -运行-gpedit.msc，左侧左侧找到计算机策略策略->> windows-> windows设置->>>>>>>>>>>>>>>>>>>>安全安全，找到用户的：以以管理员运行： 2，运行运行运行：默认管理人员运行所有程序了，你可以试一试。 ![图像](https://user-images.githubusercontent.com/24587454/218266100-4634e06b-9924-4996-82fb-3b59a6aa27b1.png)

成功了，谢谢分享，那天我忘记重启了

**Comment by 648480505** [comment]
> > > 只适用于以上系统，-运行-gpedit.msc，左侧左侧找到计算机策略策略->> windows-> windows设置->>>>>>>>>>>>>>>>>>>>>> >>>> >安全安全，找到用户的：以管理人员运行： 2，运行运行运行：默认管理人员运行所有程序了，你可以试一试。![图片](https://user-images.githubusercontent.com/24587454/218266100-4634e06b-9924-4996-82fb-3b59a6aa27b1.png)
> > 
> > 
> > 管理员，我账户所有管理员管理员，组权利限制权利限制权利限制权利限制权利限制权利限制权利限制权利限制权利限制权利限制权利限制
> 
> 测速的时候可以直接用命令执行，不用cmd命令也执行

嗯
