### ISSUE TITLE
请问这个错误如何解决

### ISSUE THREAD

**Issue by zzazhaoziao** [PauperZ/SSRSpeedN#54]
![屏幕截图 2023-04-19 163000](https://user-images.githubusercontent.com/44032708/233022234-e7a16bd2-bd73-427b-9746-1ac74fc7f66f.png)

**Comment by zzazhaoziao** [comment]
![屏幕截图 2023-04-19 165254](https://user-images.githubusercontent.com/44032708/233022643-d73f0127-d309-4ca3-b68e-2f5040588be9.png)

**Comment by zzazhaoziao** [comment]
![屏幕截图 2023-04-19 174541](https://user-images.githubusercontent.com/44032708/233036623-1d7713fb-5599-4618-b214-7fe106ea85a0.png)

**Comment by zzazhaoziao** [comment]
自己尝试手动安装依赖依然报错

**Comment by 648480505** [comment]
> 自己尝试手动安装依赖依然报错

下载源代码安装https://files.pythonhosted.org/packages/ff/db/ddaa52e3df42415231cbaf1d2f10593072cddf8317d743c5bb05fba2c2fb/pynat-0.7.0.tar.gz

**Comment by zzazhaoziao** [comment]
已解决，降级python以及pip版本，以及改为测shadowrocket链接
